### ISSUE TITLE
AcquireTokenAsync timeout when called asynchronously

### ISSUE THREAD

**Issue by devigned** [AzureAD/azure-activedirectory-library-for-dotnet#248]
Per issue: https://github.com/Azure/azure-sdk-for-net/issues/1432 the user has an MVC app that is hanging on AcquireTokenAsync. Any thoughts on why this is hanging?

**Comment by kpanwar** [comment]
Not really. The simplest way for the developer is to try out the sample apps published at https://github.com/AzureADSamples to repro the problem and eliminate any user configuration issues.

**Comment by devigned** [comment]
@kpanwar I don't see any public repos there. Did you mean some other uri?

**Comment by kpanwar** [comment]
Its https://msdn.microsoft.com/en-us/library/azure/dn646737.aspx that has all the samples list.

**Comment by kpanwar** [comment]
@devigned - Did this issue resolve for you? I did some read up and found out that this could happening if you don't call configureAwait(false) on your method calls.

**Comment by devigned** [comment]
It wasn't a problem I personally was running into. It was a customer issue in the referenced github issue.

I think it would have been most effective to interact with them directly in the other thread, but I think that time has past considering it was 201 days ago the issue was posted.

I'll close this issue.

**Comment by smoothdeveloper** [comment]
@devigned @kpanwar I'm facing same issues now, been spending a day trying to figure out what is wrong with that sole call.

If I cancel evaluation and run another call, the task will eventually resolve, I have 0 clue how to get this working in my actual application code.

Since my only intent is to get a hold of credentials for most of the management APIs, wouldn't it make sense for MS to help azure developers (the ones who pay subscriptions and develop services running on Azure) by, why not, providing authentication in a very simple manner, not involving configuring zillions of things with Azure Active Directory.

A simple idea like say giving a certificate + a client ID defined in a very simple screen in the portal (provide a download link of a file with certificate and client id that can be loaded by application code), that ought to be enough and light years better than the inflicted Active Directory stuff with 0 alternatives.

I'm only few days in working with azure, many things are great, but dealing with Active Directory is not:
* setting up things in portal which doesn't make any sense for my use
* looking up AD APIs in a jungle of outdated stuff online, mostly with poor code quality
* picking a sample among 56 samples (do we really need 56 samples to understand 3 lines of  authentication code? are those samples really getting to the point?)
* code still freezing on `AcquireTokenAsync` and when I get past this, I get unhelpful error message, even after successfully authenticating the user in a browser (which I don't want to expose my end users to)

This is so some day I'll get hold of `ComputeManagementClient` instance, many developers are spending days on this stuff without a good reason.

On the other hand, I've been able to use mbrace running cloudservice with absolutely 0 headache, it just works, I downloaded a .publishsettings and I was done, mbrace is not even a microsoft project and they somehow succeed to put the end-user first in terms of ease of setup / no-nonsense.

Please enable Active Directory-less authentication for all APIs.

**Comment by kpanwar** [comment]
Did you put configure await as false as previously suggested?

**Comment by kpanwar** [comment]
Also the feedback you provide is being addressed in the new version of the portal (not part of aad). Aad is just another service offered in azure.can you share details around the stuff that is outdated in azure ad samples? There are multiple samples because each one addresses the use of the libraries for different combination of scenarios.

**Comment by akonyer** [comment]
The problem for me was that I was not using "async all the way down".

There were places I was using async/await, and then other places I was forcing it to be synchronous by calling .Result, which was causing a deadlock. I'm not 100% sure why the deadlock was happening, but using async all the day down did solve the issue.

It is good practice in general when you are working with async code.

Hopefully this helps you with your issue.

**Comment by smoothdeveloper** [comment]
@kpanwar thanks for your help.

> Also the feedback you provide is being addressed in the new version of the portal (not part of aad). Aad is just another service offered in azure.

Is there a way I can get a `ComputeManagementClient` and a `SqlManagementClient` without Azure Active Directory?

> Did you put configure await as false as previously suggested?

I'm trying this now:

```fsharp
module Authentication =
  open Microsoft.IdentityModel.Clients.ActiveDirectory
  open Microsoft.Rest
  
  let authenticate (settings: CloudSettings) =
    let authenticationContext =
      settings.ActiveDirectoryAuthenticationUrl
      |> AuthenticationContext
  
    let userCredential =
      UserPasswordCredential(settings.ActiveDirectoryLogin, settings.ActiveDirectoryPassword)
    
    authenticationContext.AcquireTokenAsync(settings.ServiceManagementUrl, settings.ActiveDirectoryClientId, userCredential)


let settings = 
  "settingsfilename"
  |> AzureSettingsLoader.GetCloudSettings // this is just loading our settings file with correct info, such as certificate, subscription id
  |> Option.get

let task = Authentication.authenticate settings
task.ConfigureAwait false
task.Result // stuck here
```

When I run this in interactive environment, I'm still getting no result and deadlocked thread, the same in the C# code of my application.

@kpanwar sorry for my ignorance, but what are the implications for calling `ConfigureAwait` with `true` or `false` or not calling it on the returned task? if it is needed to call it with false, should this be done in the API?

Could the API expose simple blocking methods (there can be a proeminent remark in the documentation) as the async handling seem to involve knowing how to avoid pitfalls if one attempts a call to `.Result`.

> can you share details around the stuff that is outdated in azure ad samples?

Actually that outdated part was referring to search on internet, I doubt there is much Microsoft can do, and it is for end users to filter out old contents which doesn't apply.

On the other hand what is under Microsoft control is the AD samples, there are 56 samples! I haven't looked at many but I'd recommend to have only a single page per language and focus on the task at hand (handling `authenticationContext.AcquireToken*`).

Keep the samples short and focused, developers know enough how to integrate in console app, web service or whatever, they don't need a sample for every "project type template coming with visual studio" but just concise and canonical instructions.

Full fledged samples should be invested on, but they should be larger "end-to-end" applications which showcase the shiny aspects of Azure and with great focus on code quality for architectural footprint.

Also in github tickets and places indexed on the web, please don't use only shortnames (such as aad, rm, etc.) this is confusing for new comers and doesn't help with contents being indexed in search engines.

on other ticket @devigned commented:

> I bet someone forgot a ConfigureAwait(false) and it never gets back to the right thread.

And I couldn't figure out if he meant this was intended to be part of the SDK code or client code, it is too short explanation to help users facing same issue.

I understand the volume of exchanges on github issues & all warrants to keep things short, but you want information to acrete in a canonical manner.

I hope my feedback will help all of you making the product better and facilitating the work of end users integration those APIs.

Thanks a lot for quick assistance!

**Comment by smoothdeveloper** [comment]
Just a short update: I downgraded to 2.19.208020213 and our problem vanished, both sync and async methods work.
